//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public int PersonasId { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
